version: '2'
services:
  db:
    image: postgres:16
    user: root
    environment:
      - POSTGRES_USER=${SERVICE_USER_POSTGRES:-odoo}
      - POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRES:-odoo17@2023}
      - POSTGRES_DB=postgres
    restart: always             # run as a service
    volumes:
      - type: bind
        source: ./postgresql
        target: /var/lib/postgresql/data
        is_directory: true

  odoo17:
    image: odoo:17
    user: root
    depends_on:
      - db
    ports:
      - "10017:8069"
      - "20017:8072" # live chat
    tty: true
    command: --
    environment:
      - HOST=db
      - USER=${SERVICE_USER_POSTGRES:-odoo}
      - PASSWORD=${SERVICE_PASSWORD_POSTGRES:-AJkKqARNe2Xj4n35Bh}
      # Odoo web interface URL
      - SERVICE_FQDN_ODOO_8069
      # Live chat URL
      - SERVICE_FQDN_CHAT_8072=/longpolling
      # Admin password for Odoo
      - ADMIN_PASSWORD=${SERVICE_PASSWORD_ODOO:-Uv53vANElNY7YoWEnL}
    volumes:
      - type: bind
        source: ./entrypoint.sh
        target: /entrypoint.sh
        content: |
          #!/bin/bash
          
          set -e
          
          # Install system dependencies
          apt-get update
          apt-get install -y build-essential python3-dev libldap2-dev libsasl2-dev libssl-dev
          
          # set the postgres database host, port, user and password according to the environment
          # and pass them as arguments to the odoo process if not present in the config file
          : ${HOST:=${DB_PORT_5432_TCP_ADDR:='db'}}
          : ${PORT:=${DB_PORT_5432_TCP_PORT:=5432}}
          : ${USER:=${DB_ENV_POSTGRES_USER:=${POSTGRES_USER:=${SERVICE_USER_POSTGRES:-'odoo'}}}}
          : ${PASSWORD:=${DB_ENV_POSTGRES_PASSWORD:=${POSTGRES_PASSWORD:=${SERVICE_PASSWORD_POSTGRES:-'AJkKqARNe2Xj4n35Bh'}}}}
          
          # Update Odoo config with admin password
          if [ -n "$ADMIN_PASSWORD" ]; then
              sed -i "s/admin_passwd = .*/admin_passwd = $ADMIN_PASSWORD/" /etc/odoo/odoo.conf
          fi
          
          # Clean apt cache to reduce image size
          apt-get clean
          rm -rf /var/lib/apt/lists/*
          
          # install python packages
          pip3 install pip --upgrade
          pip3 install -r /etc/odoo/requirements.txt
          
          DB_ARGS=()
          function check_config() {
              param="$1"
              value="$2"
              if grep -q -E "^\s*\b${param}\b\s*=" "$ODOO_RC" ; then       
                  value=$(grep -E "^\s*\b${param}\b\s*=" "$ODOO_RC" |cut -d " " -f3|sed 's/["\n\r]//g')
              fi;
              DB_ARGS+=("--${param}")
              DB_ARGS+=("${value}")
          }
          check_config "db_host" "$HOST"
          check_config "db_port" "$PORT"
          check_config "db_user" "$USER"
          check_config "db_password" "$PASSWORD"
          
          case "$1" in
              -- | odoo)
                  shift
                  if [[ "$1" == "scaffold" ]] ; then
                      exec odoo "$@"
                  else
                      wait-for-psql.py ${DB_ARGS[@]} --timeout=30
                      exec odoo "$@" "${DB_ARGS[@]}"
                  fi
                  ;;
              -*)
                  wait-for-psql.py ${DB_ARGS[@]} --timeout=30
                  exec odoo "$@" "${DB_ARGS[@]}"
                  ;;
              *)
                  exec "$@"
          esac
          
          exit 1
      - type: bind
        source: ./addons
        target: /mnt/extra-addons
        is_directory: true
      - type: bind
        source: ./etc
        target: /etc/odoo
        is_directory: true
      - type: bind
        source: ./etc/odoo.conf
        target: /etc/odoo/odoo.conf
        content: |
          [options]
          addons_path = /mnt/extra-addons
          data_dir = /etc/odoo
          admin_passwd = ${SERVICE_PASSWORD_ODOO:-Uv53vANElNY7YoWEnL}
      - type: bind
        source: ./etc/requirements.txt
        target: /etc/odoo/requirements.txt
        content: |
          # Official Odoo 17 Python Package Requirements
          # Based on Ubuntu 22.04 and Debian 11 python3-* equivalents
          
          Babel==2.9.1
          chardet==4.0.0
          cryptography==3.4.8
          decorator==4.4.2
          docutils==0.17
          ebaysdk==2.1.5
          freezegun==1.1.0
          geoip2==2.9.0
          gevent==21.8.0 ; python_version == '3.10'
          gevent==22.10.2; python_version > '3.10'
          greenlet==1.1.2 ; python_version == '3.10'
          greenlet==2.0.2 ; python_version > '3.10'
          idna==2.10
          Jinja2==3.0.3 ; python_version <= '3.10'
          Jinja2==3.1.2 ; python_version > '3.10'
          libsass==0.20.1
          lxml==4.8.0 ; python_version <= '3.10'
          lxml==4.9.2 ; python_version > '3.10'
          MarkupSafe==2.0.1 ; python_version <= '3.10'
          MarkupSafe==2.1.2 ; python_version > '3.10'
          num2words==0.5.10
          ofxparse==0.21
          passlib==1.7.4
          Pillow==9.0.1 ; python_version <= '3.10'
          Pillow==9.4.0 ; python_version > '3.10'
          polib==1.1.1
          psutil==5.9.0 ; python_version <= '3.10'
          psutil==5.9.4 ; python_version > '3.10'
          psycopg2==2.9.2 ; sys_platform != 'win32' and python_version <= '3.10'
          psycopg2==2.9.5 ; python_version > '3.10' or sys_platform == 'win32'
          pydot==1.4.2
          pyopenssl==21.0.0
          PyPDF2==1.26.0 ; python_version <= '3.10'
          PyPDF2==2.12.1 ; python_version > '3.10'
          pypiwin32 ; sys_platform == 'win32'
          pyserial==3.5
          python-dateutil==2.8.1
          python-ldap==3.4.0 ; sys_platform != 'win32'
          python-stdnum==1.17
          pytz
          pyusb==1.2.1
          qrcode==7.3.1
          reportlab==3.6.8 ; python_version <= '3.10'
          reportlab==3.6.12 ; python_version > '3.10'
          requests==2.25.1
          rjsmin==1.1.0
          urllib3==1.26.5
          vobject==0.9.6.1
          Werkzeug==2.0.2
          xlrd==1.2.0
          XlsxWriter==3.0.2
          xlwt==1.3.*
          zeep==4.1.0

          # Additional Python Packages
          pycryptodome==3.20.0
          paramiko==2.12.0
    restart: always             # run as a service
    